### ISSUE TITLE
Add some blocks that can`t be destroied like bedrock ,"jiyan" 

### ISSUE THREAD

**Issue by SoonIter** [vyse12138/minecraft-threejs#9]
Unlimited fall, from sky to underground to sky, makes me horrified.
How can I contact u? a group or a private social media.
I want to query something about "Three.js" and "WebGL" .
Hope to have more discussion.

**Comment by vyse12138** [comment]
Hey, thanks for the suggestion! Theoretically u shouldn't be able to experience unlimited fall since the world are dynamically generated when you are destroying blocks. However, I do like the idea of adding a layer of bedrocks into the game!

If u are happy to make a PR on it, I will be very pleased to review and merge it! Otherwise, I might just add this feature in the next couple of days / weeks.

Regarding reaching me out, there's currently no group for this project, however,  u can email me on yulei.zhu@outlook.com to chat more.

YZ

**Comment by yulei-movember** [comment]
bedrock added at commit https://github.com/vyse12138/minecraft-threejs/commit/3525791ae25681308a3b536bc27d3f0b92527fe4

**Comment by vyse12138** [comment]
bedrock added at commit https://github.com/vyse12138/minecraft-threejs/commit/3525791ae25681308a3b536bc27d3f0b92527fe4
